name: hochzeits_planer
description: "A new Flutter project."

publish_to: 'none'

version:  1.1.0+10

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
      # Export-Dependencies
  pdf: ^3.10.0
  printing: ^5.11.0
  excel: ^4.0.6
  path_provider: ^2.1.4
  share_plus: ^7.2.1
  file_picker: ^8.0.0+1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
 

    # NEU fÃ¼r Dienstleister
  fl_chart: ^0.66.0
  url_launcher: ^6.2.2

  # UI
  cupertino_icons: ^1.0.8

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Utilities
  intl: ^0.18.1
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

   